### ISSUE TITLE
How to specify storage

### ISSUE THREAD

**Issue by step-xiaoyu-ka** [RUB-SysSec/EthBMC#6]
Hi, I thought about the example for analysing the parity hack:

```
state: 
    # Wallet
    0xad62f08b3b9f0ecc7251befbeff80c9bb488fe9:
        balance: 0x8AC7230489E80000
        nonce: 0x0
        code: 606060...
        storage:
            0x0: 0xcafecafecafecafecafecafecafecafecafecafe # "owner"

    # Receiver
    0xcafecafecafecafecafecafecafecafecafecafe:
        balance: 0x0
        nonce: 0x0
        code: 60606...

victim: 0xad62f08b3b9f0ecc7251befbeff80c9bb488fe9
```

The item of storage seems to be the key for inter-contract analysis, but how do I determine which storage variable(0x0 in your example) corresponds to the library contract address for different contracts(maybe 0x2).

Besides, for the contracts whose source code is available, we can learn the information of storage from the contract ABI(The storage with`"type":"address"`may represent a library contract), what about ones without source code.

Finally, if the address of Receiver is not explicitly indicated in Sender's storage, inter-contract analysis is not performed. Is it right?
